/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6  for MT8127. Copyright MediaTek Inc. (C) 2013.
 * Fri Jan 16 19:37:07 2015
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


